PREFIX schema: <http://schema.org/>
PREFIX n3: <http://schema.org/>
SELECT 
  ?attraction
  ?name
  ?description
  (IRI(?url) AS ?strurl)
  (GROUP_CONCAT(?image; SEPARATOR=", ") AS ?imagesList)
WHERE {
  ?attraction a <http://schema.org/TouristAttraction> .
  ?attraction n3:name ?name .
  ?attraction n3:description ?description .
  ?attraction n3:url ?url .
  ?attraction n3:image ?image .
  FILTER (langMatches(lang(?name), lang(?description))) .
} GROUP BY ?attraction ?name ?description ?url